name: Producer Fee Calculation
on:
  schedule:
    # Customize schedule expression at crontab.guru
    # currently running at 12pm UTC every Friday
    - cron: "0 12 * * FRI"
  workflow_dispatch:
    #  allow manual updating

jobs:
  scrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npx playwright install-deps chromium
      - run: ./bin/producer_payments.js  --headless
        env:
          LFM_USERNAME: ${{ secrets.LFM_USERNAME }}
          LFM_PASSWORD: ${{ secrets.LFM_PASSWORD }}
